## Service definition ##
application:
  schemaVersion: 1.0.0-preview2
  name: MdDevDaysDemo2019
  properties:
    services:
      - name: DeliveryService
        properties:
          description: DeliveryService description.
          osType: Windows
          codePackages:
            - name: DeliveryService
              image: deliveryservice:dev
              volumes:
              - name: sfvol
                creationParameters:
                  kind: ServiceFabricVolumeDisk
                  sizeDisk: Small
                destinationPath: C:\app\data
              endpoints:
                - name: DeliveryServiceListener
                  port: 80
#              environmentVariables:
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: "[parameters('DeliveryService_cpu')]"
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: MdDevDaysDemo2019Network
              endpointRefs:
                - name: DeliveryServiceListener
